server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
  undertow:
    threads:
      io: 4   # Define a quantidade de threads de I/O (Input/Output). Responsáveis por gerenciar conexões e processar requisições.
      worker: 64    # Define a quantidade de threads de trabalho, que executam as requisições processadas pelas threads de I/O.
    buffer-size: 2048
    direct-buffers: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dotflix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari: # É pool de conexões para bancos de dados em aplicações Java de alto desempenho, cria e reutiliza as conexões, garantindo mais desempenho
      auto-commit: false  # Melhora o desempenho
      connection-timeout: 250 # Tempo de espera para uma thread conseguir uma conexão do pool
      max-lifetime: 600000  # Tempo máximo que uma conexão fica aberta
      maximum-pool-size: 20  # Número máximo de conexões do pool
      minimum-idle: 10  #
      pool-name: master
  jpa:
    open-in-view: false # Não abre conexão com o banco desde o controller, melhorando o desempenho
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      hibernate:
        format_sql: true
  flyway:
    url: ${POSTGRES_URL}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
