name: dotflix-ci
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adoptopenjdk'

      - name: Build with gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test