---
name: dotflix-ci

on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17, 21, 23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Build with gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install docker-compose
        uses: sudo apt install docker-compose

      - name: Execute docker-compose
        uses: sudo docker-compose up -d