name: dotflix-ci
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '17', '21', '23' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adoptopenjdk'

      - name: Build with gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test